version: '2'

services:
  demo:
    image: "jdchain-demo:1.3.0"
    container_name: jdchain-demo
    networks:
      jdchain_default:
        aliases:
          - demo
    hostname: demo
    restart: always
    ports:
      - "11010:11010"
      - "7080:7080"
      - "10080:10080"
      - "10081:10081"
      - "11011:11011"
      - "7081:7081"
      - "10082:10082"
      - "10083:10083"
      - "11012:11012"
      - "7082:7082"
      - "10084:10084"
      - "10085:10085"
      - "11013:11013"
      - "7083:7083"
      - "10086:10086"
      - "10087:10087"
      - "8080:8080"
#    volumes:
#      - "./logs:/export/jdchain/peer0/logs"

networks:
  jdchain_default:
    driver: bridge
